language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "ceciliacal"
    token: "ac6d5799265eb297b8b56fdac3264e2040d45265" 

script:
  - ant build
  - sonar-scanner

 



