language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "ceciliacal"
    token: "5df0dedf6e6bfdc05a7f5404d0927102861cf159" 

script:
  - ant build
  - sonar-scanner

 



