language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "ceciliacal"
    token: "bafc00e701bb7003e4c4bace5a4895a92f20e9ae" 

script:
  - ant build
  - sonar-scanner
  
 



